- hosts: all
  become: yes
  tasks: 
    - name: purging previous services
      shell: | 
         if [ `kubectl get deploy | grep -v NAME | awk '{print $1}' | grep myapp | wc -l` -gt 0 ]; then  
            kubectl delete deploy `kubectl get deploy | grep -v NAME | awk '{print $1}' | grep myapp`
         else 
            echo "No app deployments found"
         fi
         if [ `kubectl get svc | grep myapp-svc  | awk '{print $1}' | wc -l` -gt 0 ]; then
            kubectl delete svc `kubectl get svc | grep myapp-svc | awk '{print $1}'`
         else
            echo "No app service found"
         fi
    - name: deploy application
      shell: kubectl create deploy myapp --image=niloydebnath/abctechnologies:latest
    - name: configure replicas 
      shell: kubectl scale deploy myapp --replicas=2
    - name: deploy service
      shell: kubectl expose deploy myapp --name myapp-svc --port 8080 --type NodePort
